
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-13
owner: ucsb-cs156-f24
repo_name: team02-f24-13
pull_requests: [{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-form","number":69,"title":"As articles form","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/69"},{"author":{"id":"MDQ6VXNlcjY2ODYwNDEw","is_bot":false,"login":"shivanimadhan","name":"Shivani Madhan"},"headRefName":"shivanimadhan-create-fixtures","number":68,"title":"create fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/68"},{"author":{"id":"MDQ6VXNlcjY2ODYwNDEw","is_bot":false,"login":"shivanimadhan","name":"Shivani Madhan"},"headRefName":"shivanimadhan-CRUD-API","number":67,"title":"added backend files","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/67"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-UCSBDiningCommonsMenuItem-table","number":66,"title":"Ez ucsb dining commons menu item table","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/66"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-UCSBDiningCommonsMenuItem-components","number":65,"title":"form components + tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/65"},{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-fixures","number":64,"title":"As articles fixures","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/64"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-UCSBDiningCommonsMenuItem-fixtures","number":63,"title":"create fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/63"},{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-backend","number":62,"title":"As articles backend","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/62"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-UCSBDiningCommonsMenuItem-backend","number":61,"title":"set up backend API for CRUD operations","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/61"}]
