
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-13
owner: ucsb-cs156-f24
repo_name: team02-f24-13
pull_requests: [{"author":{"id":"U_kgDOCMRqBA","is_bot":false,"login":"AnvithaKosuri","name":""},"headRefName":"helpRequestTable","number":106,"title":"Help request table","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/106"},{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-Copy","number":105,"title":"As articles copy","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/105"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-MenuItemReview-realedit","number":104,"title":"dq-MenuItemReview edit page recreated","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/104"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-MenuItemReview-realindex","number":103,"title":"dq-MenuItemReview index page recreated","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/103"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-MenuItemReview-realcreate","number":102,"title":"dq-MenuItemReview create page recreated","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/102"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-MenuItemReview-realplaceholder","number":101,"title":"dq-MenuItemReview placeholder recreated","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/101"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-MenuItemReview-realtable","number":100,"title":"dq-MenuItemReview table recreated","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/100"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-MenuItemReview-realform","number":99,"title":"dq-MenuItemReview form recreated","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/99"},{"author":{"id":"U_kgDOCMRqBA","is_bot":false,"login":"AnvithaKosuri","name":""},"headRefName":"formComponentHelpRequest","number":93,"title":"last change went wrong because of hard remove, this is working well now, passed storybook and coverage tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/93"},{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-Table","number":70,"title":"As articles table","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/70"}]
