
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-13
owner: ucsb-cs156-f24
repo_name: team02-f24-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-DCMI-index","number":112,"title":"Ez dcmi index","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/112"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-DCMI-edit","number":111,"title":"Ez dcmi edit","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/111"},{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-Edit","number":110,"title":"As articles edit","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/110"},{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-Create","number":109,"title":"As articles create","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/109"},{"author":{"id":"U_kgDOCMRqBA","is_bot":false,"login":"AnvithaKosuri","name":""},"headRefName":"copyPlaceHolderHelpRequest","number":108,"title":"Copy place holder help request and ran coverage tests ran","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/108"},{"author":{"id":"U_kgDOCMRqBA","is_bot":false,"login":"AnvithaKosuri","name":""},"headRefName":"finalFormComponentHelpRequest","number":107,"title":"changes with form and table, aligns with main","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/107"}]
