
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-13
owner: ucsb-cs156-f24
repo_name: team02-f24-13
pull_requests: [{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-MenuItemReview-pages","number":87,"title":"dq-added MenuItemReview index, create, edit pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/87"},{"author":{"id":"MDQ6VXNlcjY2ODYwNDEw","is_bot":false,"login":"shivanimadhan","name":"Shivani Madhan"},"headRefName":"shivanimadhan-form-component","number":74,"title":"Shivanimadhan form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/74"},{"author":{"id":"U_kgDOB3ED6g","is_bot":false,"login":"Anteater10","name":""},"headRefName":"AS-Articles-Table","number":70,"title":"As articles table","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/70"},{"author":{"id":"MDQ6VXNlcjY2ODYwNDEw","is_bot":false,"login":"shivanimadhan","name":"Shivani Madhan"},"headRefName":"shivanimadhan-create-fixtures","number":68,"title":"create fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/68"}]
