title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-13
owner: ucsb-cs156-f24
repo_name: team02-f24-13
pull_requests: [{"author":{"id":"U_kgDOCMRqBA","is_bot":false,"login":"AnvithaKosuri","name":""},"headRefName":"integrationTestHelpRequest","number":137,"title":"Integration test help request","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/137"},{"author":{"id":"MDQ6VXNlcjY2ODYwNDEw","is_bot":false,"login":"shivanimadhan","name":"Shivani Madhan"},"headRefName":"shivanimadhan-edit-page","number":136,"title":"added edit files","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/136"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-DCMI-endtoend","number":135,"title":"Ez dcmi endtoend","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/135"},{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"steven-team03-e2e","number":134,"title":"End 2 End Tests for RecommendationRequestTable","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/134"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-DCMI-integrationtest","number":133,"title":"ez added integration test","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/133"},{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"steven-team03","number":132,"title":"Integration Tests for RecommendationRequestTable","url":"https://github.com/ucsb-cs156-f24/team02-f24-13/pull/132"}]
